# fly.toml app configuration file generated for crossfit-reservas-mvp on 2025-08-10T23:16:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crossfit-reservas-mvp'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true     # Apaga máquinas adicionales sin tráfico
  auto_start_machines = true    # Inicia máquinas automáticamente con requests
  min_machines_running = 1      # Mantiene siempre al menos 1 máquina activa

[env]
  TZ = "America/Santiago"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
