# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Activar magicbox-reserva a las 17:00 Chile
on:
  schedule:
    - cron: '0 20 * * *'  # corresponde a 17:00 CLT (UTC−3)
jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest
      - name: Activar aplicación Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl status --app magicbox-reserva || flyctl deploy --app magicbox-reserva
