name: Ventana Fly (crossfit-reservas-mvp · 17:00–20:00 CL)

on:
  schedule:
    # START exacto a las 17:00 CL
    - cron: "0 21 * * *"   # Invierno CL (UTC-4): 17:00 = 21:00 UTC
    - cron: "0 20 * * *"   # Verano  CL (UTC-3): 17:00 = 20:00 UTC
    # STOP exacto a las 20:00 CL
    - cron: "0 0 * * *"    # Invierno CL: 20:00 = 00:00 UTC (día siguiente)
    - cron: "0 23 * * *"   # Verano  CL: 20:00 = 23:00 UTC
  workflow_dispatch: {}

jobs:
  control:
    runs-on: ubuntu-latest
    env:
      APP: crossfit-reservas-mvp
      FLY_API_HOSTNAME: https://api.machines.dev
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      TARGET_ID: d891dd0ae45618
    steps:
      - name: Instalar jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Listar machines
        run: |
          curl -fsSL -H "Authorization: Bearer $FLY_API_TOKEN" \
            "$FLY_API_HOSTNAME/v1/apps/$APP/machines" -o machines.json
          jq -r '.[].id' machines.json

      - name: START (solo 17:00)
        if: github.event.schedule == '0 21 * * *' || github.event.schedule == '0 20 * * *'
        run: |
          echo "▶️ START $TARGET_ID"
          curl -fsS -X POST -H "Authorization: Bearer $FLY_API_TOKEN" \
            "$FLY_API_HOSTNAME/v1/apps/$APP/machines/$TARGET_ID/start"
          curl -fsS "https://$APP.fly.dev/health" || true

      - name: STOP (solo 20:00)
        if: github.event.schedule == '0 0 * * *' || github.event.schedule == '0 23 * * *'
        run: |
          echo "⏹ STOP $TARGET_ID"
          curl -fsS -X POST -H "Authorization: Bearer $FLY_API_TOKEN" \
            "$FLY_API_HOSTNAME/v1/apps/$APP/machines/$TARGET_ID/stop"